// This file is auto-generated by packages/periphery/script/gen-const-package-info.ts
export const packageInfo = [
  {
    packageName: "@ts-validator-adapter/ajv",
    shortName: "ajv",
    name: "Ajv",
    homepage: "https://ajv.js.org/",
  },
  {
    packageName: "@ts-validator-adapter/arktype",
    shortName: "arktype",
    name: "ArkType",
    homepage: "https://arktype.dev/",
  },
  {
    packageName: "@ts-validator-adapter/typebox",
    shortName: "typebox",
    name: "TypeBox",
    homepage: "https://github.com/sinclairzx81/typebox",
  },
  {
    packageName: "@ts-validator-adapter/valibot",
    shortName: "valibot",
    name: "Valibot",
    homepage: "https://valibot.dev/",
  },
  {
    packageName: "@ts-validator-adapter/zod",
    shortName: "zod",
    name: "Zod",
    homepage: "https://zod.dev/",
  },
  {
    packageName: "@ts-validator-adapter/zod-mini",
    shortName: "zod-mini",
    name: "Zod Mini",
    homepage: "https://zod.dev/",
  },
] as const;
