import { writeFileSync } from "fs";
import { resolve } from "path";
import { getAdaptersInfo } from "../src/util";

function genConstPackageInfo() {
  const adaptersInfo = getAdaptersInfo();
  return `// This file is auto-generated by packages/periphery/script/gen-const-package-info.ts
export const packageInfo = [
${adaptersInfo
  .map((info) => `  {
    packageName: "${info.packageName}",
    shortName: "${info.shortName}",
    name: "${info.name || ''}",
    homepage: "${info.homepage || ''}",
  }`)
  .join(",\n")},
] as const;
`;
}

function genConstPackageInfoFile() {
  const content = genConstPackageInfo();
  const filePath = resolve(import.meta.dirname, "../src/constant/package-info.ts");
  writeFileSync(filePath, content, { encoding: "utf-8" });
  console.log(`File written to ${filePath}`);
}

genConstPackageInfoFile();
