name: CI

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Set up .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_PAT }}" > ~/.npmrc
          echo "@fneco:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
