---
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project
        uses: ./.github/actions/setup-project
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}

      - name: Run tests
        run: pnpm test
